### ISSUE TITLE
esp softap_prov (3.3.1)

### ISSUE THREAD

**Issue by gulkanguner** [espressif/esp-idf-provisioning-android#14]
Hi, I have some problem that i can not handle. I am using esp32-Wroom with esp-idf 3.3.1. I have succesfuly run the softap_prov example with the esp_prov.py. Then I have tried to run this esp-idf-provisioning-android project in android studio and it was not succesfully run.  
![Untitled](https://user-images.githubusercontent.com/31211766/85137541-0cc85100-b24a-11ea-9d97-c0fb44addb95.png)
The app gets stuck here and it doesn't go any further. I'm thinking that this esp-idf version may not mach the prov-android version.  
The problem that i understand is application waiting a json string but it gets something else

I am getting this part of Logs from Android Studio below: 

> D/ESP:ESPDevice: enableOnlyWifiNetwork()
E/ESP:ESPDevice: Network is available - 3
D/NetdClient: setNetworkForTarget(268)
D/ESP:ESPDevice: Connecting to device
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
**D/ESP:ESPDevice: Value : V0.1
E/ESP:ESPDevice: Schedule wifiConnectionFailedTask
W/System.err: org.json.JSONException: Value V0.1 of type java.lang.String cannot be converted to JSONObjec**t
W/System.err:     at org.json.JSON.typeMismatch(JSON.java:111)
        at org.json.JSONObject.<init>(JSONObject.java:163)
W/System.err:     at org.json.JSONObject.<init>(JSONObject.java:176)
        at com.espressif.provisioning.ESPDevice$13$1.onSuccess(ESPDevice.java:1039)
        at com.espressif.provisioning.transport.SoftAPTransport$1.run(SoftAPTransport.java:112)
W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
W/System.err:     at java.lang.Thread.run(Thread.java:764)
D/ESP:ESPDevice: Capabilities JSON not available.
D/ProvisionLanding: On Device Prov Event RECEIVED : 1
E/ProvisionLanding: Device Connected Event Received
I/zygote64: Do partial code cache collection, code=124KB, data=100KB
I/zygote64: After code cache collection, code=124KB, data=100KB
    Increasing code cache capacity to 512KB
W/View: dispatchProvideAutofillStructure(): not laid out, ignoring
I/chatty: uid=10203(u0_a203) com.espressif.wifi_provisioning identical 1 line
W/View: dispatchProvideAutofillStructure(): not laid out, ignoring
I/AssistStructure: Flattened final assist data: 3196 bytes, containing 1 windows, 13 views
**D/ProofOfPossessionActivity: POP : abcd1234
D/ProvisionActivity: Selected AP -null**
I/zygote64: Do full code cache collection, code=247KB, data=196KB
I/zygote64: After code cache collection, code=243KB, data=136KB
>

**Comment by khushbushah2302** [comment]
@gulkanguner , 
We have fixed this issue. Please take update of esp-idf-provisioning-android project and check.

**Comment by gulkanguner** [comment]
> 
> 
> @gulkanguner ,
> We have fixed this issue. Please take update of esp-idf-provisioning-android project and check.

Thanks a lot. It worked.
I have different problem now. After I send wifi credentials via android-app, my esp32 get it and connected to wifi, but _**checking provisioning status**_ has failed in android-app.
![Capture](https://user-images.githubusercontent.com/31211766/85408344-0fd68080-b56d-11ea-8619-828d703474f9.PNG)
**part of my softapp logs:**

> I (1455) app: SoftAP started
I (1465) app_prov: SoftAP Provisioning started with SSID 'PROV_8BDCD1', Password 'PROV_PASS'
I (16435) wifi: new:<1,0>, old:<1,0>, ap:<1,1>, sta:<255,255>, prof:1
I (16435) wifi: station: cc:61:e5:1f:59:fc join, AID=1, bgn, 20
I (16465) app: station:cc:61:e5:1f:59:fc join, AID=1
I (16605) tcpip_adapter: softAP assign IP to station,IP is: 192.168.4.2
I (68335) app_prov_handler: WiFi Credentials Received :
        ssid 8BitizAP
        password aborogandi75
I (68405) wifi: mode : sta (b4:e6:2d:8b:dc:d1) + softAP (b4:e6:2d:8b:dc:d2)
I (68435) app_prov_handler: WiFi Credentials Applied
I (68435) app_prov: STA Start
I (69415) wifi: switch to channel 4
I (69415) wifi: ap channel adjust o:1,1 n:4,1
I (69415) wifi: new:<4,0>, old:<1,0>, ap:<4,1>, sta:<0,0>, prof:1
I (69415) wifi: new:<4,1>, old:<4,0>, ap:<4,1>, sta:<4,0>, prof:1
I (70405) wifi: state: init -> auth (b0)
I (70415) wifi: state: auth -> assoc (0)
I (70415) wifi: state: assoc -> run (10)
I (70675) wifi: connected with 8BitizAP, aid = 3, channel 4, BW20, bssid = 40:4a:03:08:2b:e8
I (70675) wifi: security type: 3, phy: bgn, rssi: -81
I (70685) wifi: pm start, type: 1

I (70835) wifi: AP's beacon interval = 102400 us, DTIM period = 1
I (72175) event: sta ip: 192.168.1.213, mask: 255.255.255.0, gw: 192.168.1.1
I (72175) app_prov: STA Got IP
I (72175) app: got ip:192.168.1.213
I (73195) app_prov_handler: Connected state
I (101665) wifi: new:<4,0>, old:<4,1>, ap:<4,1>, sta:<4,0>, prof:4
I (101665) wifi: station: cc:61:e5:1f:59:fc join, AID=1, bgn, 20
I (101695) app: station:cc:61:e5:1f:59:fc join, AID=1
I (101805) tcpip_adapter: softAP assign IP to station,IP is: 192.168.4.2
I (102175) app_prov: Stopping provisioning
I (102275) wifi: station: cc:61:e5:1f:59:fc leave, AID = 1, bss_flags is 134243, bss:0x3ffba4a4
I (102275) wifi: new:<4,0>, old:<4,0>, ap:<4,1>, sta:<4,0>, prof:4
I (102275) wifi: mode : sta (b4:e6:2d:8b:dc:d1)
I (102285) app: station:cc:61:e5:1f:59:fcleave, AID=1
I (102285) app: SoftAP stopped
I (102285) app_prov: Provisioning stopped

> 

**and android-app logs :**

>

06/23 13:28:13: Launching 'app' on motorola XT1650.
$ adb shell am start -n "com.espressif.wifi_provisioning/com.espressif.ui.activities.EspMainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Connected to process 7494 on device 'motorola-xt1650-ZY223QNJQL'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
I/zygote64: Do partial code cache collection, code=30KB, data=19KB
I/zygote64: After code cache collection, code=30KB, data=19KB
    Increasing code cache capacity to 128KB
I/zygote64: Rejecting re-init on previously-failed class java.lang.Class<androidx.core.view.ViewCompat$2>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/view/View$OnUnhandledKeyEventListener;
        at void androidx.core.view.ViewCompat.setOnApplyWindowInsetsListener(android.view.View, androidx.core.view.OnApplyWindowInsetsListener) (ViewCompat.java:2421)
        at android.view.ViewGroup androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor() (AppCompatDelegateImpl.java:779)
        at void androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor() (AppCompatDelegateImpl.java:659)
        at void androidx.appcompat.app.AppCompatDelegateImpl.setContentView(int) (AppCompatDelegateImpl.java:552)
        at void androidx.appcompat.app.AppCompatActivity.setContentView(int) (AppCompatActivity.java:161)
        at void com.espressif.ui.activities.EspMainActivity.onCreate(android.os.Bundle) (EspMainActivity.java:65)
        at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:6984)
        at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1235)
        at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2797)
        at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2923)
        at void android.app.ActivityThread.-wrap11(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
        at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1616)
        at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:105)
        at void android.os.Looper.loop() (Looper.java:164)
        at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6617)
        at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
        at void com.android.internal.os.Zygote$MethodAndArgsCaller.run() (Zygote.java:240)
        at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:769)
    Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.View$OnUnhandledKeyEventListener" on path: DexPathList[[zip file "/data/app/com.espressif.wifi_provisioning-jGqQAbhxVMu6QwE1tIzLGw==/base.apk"],nativeLibraryDirectories=[/data/app/com.espressif.wifi_provisioning-jGqQAbhxVMu6QwE1tIzLGw==/lib/arm64, /system/lib64, /system/vendor/lib64]]
        at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:93)
        at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
        at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
        at void androidx.core.view.ViewCompat.setOnApplyWindowInsetsListener(android.view.View, androidx.core.view.OnApplyWindowInsetsListener) (ViewCompat.java:2421)
        at android.view.ViewGroup androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor() (AppCompatDelegateImpl.java:779)
        at void androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor() (AppCompatDelegateImpl.java:659)
        at void androidx.appcompat.app.AppCompatDelegateImpl.setContentView(int) (AppCompatDelegateImpl.java:552)
        at void androidx.appcompat.app.AppCompatActivity.setContentView(int) (AppCompatActivity.java:161)
        at void com.espressif.ui.activities.EspMainActivity.onCreate(android.os.Bundle) (EspMainActivity.java:65)
        at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:6984)
        at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1235)
        at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2797)
        at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2923)
        at void android.app.ActivityThread.-wrap11(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
        at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1616)
        at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:105)
        at void android.os.Looper.loop() (Looper.java:164)
        at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6617)
        at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
        at void com.android.internal.os.Zygote$MethodAndArgsCaller.run() (Zygote.java:240)
        at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:769)
I/zygote64: Rejecting re-init on previously-failed class java.lang.Class<androidx.core.view.ViewCompat$2>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/view/View$OnUnhandledKeyEventListener;
        at void androidx.core.view.ViewCompat.setOnApplyWindowInsetsListener(android.view.View, androidx.core.view.OnApplyWindowInsetsListener) (ViewCompat.java:2421)
        at android.view.ViewGroup androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor() (AppCompatDelegateImpl.java:779)
        at void androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor() (AppCompatDelegateImpl.java:659)
        at void androidx.appcompat.app.AppCompatDelegateImpl.setContentView(int) (AppCompatDelegateImpl.java:552)
        at void androidx.appcompat.app.AppCompatActivity.setContentView(int) (AppCompatActivity.java:161)
        at void com.espressif.ui.activities.EspMainActivity.onCreate(android.os.Bundle) (EspMainActivity.java:65)
        at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:6984)
        at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1235)
        at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2797)
        at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2923)
        at void android.app.ActivityThread.-wrap11(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
        at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1616)
        at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:105)
        at void android.os.Looper.loop() (Looper.java:164)
        at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6617)
        at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
        at void com.android.internal.os.Zygote$MethodAndArgsCaller.run() (Zygote.java:240)
        at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:769)
    Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.View$OnUnhandledKeyEventListener" on path: DexPathList[[zip file "/data/app/com.espressif.wifi_provisioning-jGqQAbhxVMu6QwE1tIzLGw==/base.apk"],nativeLibraryDirectories=[/data/app/com.espressif.wifi_provisioning-jGqQAbhxVMu6QwE1tIzLGw==/lib/arm64, /system/lib64, /system/vendor/lib64]]
        at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:93)
        at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
        at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
        at void androidx.core.view.ViewCompat.setOnApplyWindowInsetsListener(android.view.View, androidx.core.view.OnApplyWindowInsetsListener) (ViewCompat.java:2421)
        at android.view.ViewGroup androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor() (AppCompatDelegateImpl.java:779)
        at void androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor() (AppCompatDelegateImpl.java:659)
        at void androidx.appcompat.app.AppCompatDelegateImpl.setContentView(int) (AppCompatDelegateImpl.java:552)
        at void androidx.appcompat.app.AppCompatActivity.setContentView(int) (AppCompatActivity.java:161)
        at void com.espressif.ui.activities.EspMainActivity.onCreate(android.os.Bundle) (EspMainActivity.java:65)
        at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:6984)
        at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1235)
        at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2797)
        at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2923)
        at void android.app.ActivityThread.-wrap11(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
        at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1616)
        at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:105)
        at void android.os.Looper.loop() (Looper.java:164)
        at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6617)
        at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
        at void com.android.internal.os.Zygote$MethodAndArgsCaller.run() (Zygote.java:240)
        at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:769)
I/zygote64: Rejecting re-init on previously-failed class java.lang.Class<androidx.core.view.ViewCompat$2>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/view/View$OnUnhandledKeyEventListener;
        at void androidx.core.view.ViewCompat.setOnApplyWindowInsetsListener(android.view.View, androidx.core.view.OnApplyWindowInsetsListener) (ViewCompat.java:2421)
        at android.view.ViewGroup androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor() (AppCompatDelegateImpl.java:779)
        at void androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor() (AppCompatDelegateImpl.java:659)
        at void androidx.appcompat.app.AppCompatDelegateImpl.setContentView(int) (AppCompatDelegateImpl.java:552)
        at void androidx.appcompat.app.AppCompatActivity.setContentView(int) (AppCompatActivity.java:161)
        at void com.espressif.ui.activities.EspMainActivity.onCreate(android.os.Bundle) (EspMainActivity.java:65)
        at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:6984)
        at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1235)
        at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2797)
        at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2923)
        at void android.app.ActivityThread.-wrap11(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
        at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1616)
        at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:105)
        at void android.os.Looper.loop() (Looper.java:164)
        at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6617)
        at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
        at void com.android.internal.os.Zygote$MethodAndArgsCaller.run() (Zygote.java:240)
        at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:769)
    Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.View$OnUnhandledKeyEventListener" on path: DexPathList[[zip file "/data/app/com.espressif.wifi_provisioning-jGqQAbhxVMu6QwE1tIzLGw==/base.apk"],nativeLibraryDirectories=[/data/app/com.espressif.wifi_provisioning-jGqQAbhxVMu6QwE1tIzLGw==/lib/arm64, /system/lib64, /system/vendor/lib64]]
        at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:93)
        at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
        at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
        at void androidx.core.view.ViewCompat.setOnApplyWindowInsetsListener(android.view.View, androidx.core.view.OnApplyWindowInsetsListener) (ViewCompat.java:2421)
        at android.view.ViewGroup androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor() (AppCompatDelegateImpl.java:779)
        at void androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor() (AppCompatDelegateImpl.java:659)
        at void androidx.appcompat.app.AppCompatDelegateImpl.setContentView(int) (AppCompatDelegateImpl.java:552)
        at void androidx.appcompat.app.AppCompatActivity.setContentView(int) (AppCompatActivity.java:161)
        at void com.espressif.ui.activities.EspMainActivity.onCreate(android.os.Bundle) (EspMainActivity.java:65)
        at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:6984)
        at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1235)
        at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2797)
        at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2923)
        at void android.app.ActivityThread.-wrap11(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
        at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1616)
        at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:105)
        at void android.os.Looper.loop() (Looper.java:164)
        at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6617)
        at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
        at void com.android.internal.os.Zygote$MethodAndArgsCaller.run() (Zygote.java:240)
        at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:769)
D/OpenGLRenderer: HWUI GL Pipeline
I/Adreno: QUALCOMM build                   : 368094a, I26dffed9a4
    Build Date                       : 12/03/17
    OpenGL ES Shader Compiler Version: EV031.22.00.01
    Local Branch                     : mybranch29464922
    Remote Branch                    : quic/gfx-adreno.lnx.1.9.r3-rel
    Remote Branch                    : NONE
    Reconstruct Branch               : NOTHING
I/vndksupport: sphal namespace is not configured for this process. Loading /vendor/lib64/hw/gralloc.msm8996.so from the current namespace instead.
I/Adreno: PFP: 0x005ff087, ME: 0x005ff063
I/OpenGLRenderer: Initialized EGL, version 1.4
D/OpenGLRenderer: Swap behavior 2
I/vndksupport: sphal namespace is not configured for this process. Loading /vendor/lib64/hw/gralloc.msm8996.so from the current namespace instead.
I/zygote64: Do partial code cache collection, code=61KB, data=48KB
    After code cache collection, code=61KB, data=48KB
I/zygote64: Increasing code cache capacity to 256KB
D/AddDeviceActivity: Device Types : both
    isSec1 : true
I/zygote64: Do full code cache collection, code=121KB, data=97KB
I/zygote64: After code cache collection, code=94KB, data=58KB
I/zygote64: Do partial code cache collection, code=98KB, data=93KB
I/zygote64: After code cache collection, code=98KB, data=93KB
    Increasing code cache capacity to 512KB
    Compiler allocated 8MB to compile void android.widget.TextView.<init>(android.content.Context, android.util.AttributeSet, int, int)
D/ESP:ESPDevice: enableOnlyWifiNetwork()
E/ESP:ESPDevice: Network is available - 3
D/NetdClient: setNetworkForTarget(335)
D/ESP:ESPDevice: Connecting to device
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
D/ESP:ESPDevice: Value : V0.1
W/System.err: org.json.JSONException: Value V0.1 of type java.lang.String cannot be converted to JSONObject
W/System.err:     at org.json.JSON.typeMismatch(JSON.java:111)
        at org.json.JSONObject.<init>(JSONObject.java:163)
W/System.err:     at org.json.JSONObject.<init>(JSONObject.java:176)
        at com.espressif.provisioning.ESPDevice$14$1.onSuccess(ESPDevice.java:1038)
        at com.espressif.provisioning.transport.SoftAPTransport$1.run(SoftAPTransport.java:112)
W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
D/ESP:ESPDevice: Capabilities JSON not available.
D/ProvisionLanding: On Device Prov Event RECEIVED : 1
E/ProvisionLanding: Device Connected Event Received
W/View: dispatchProvideAutofillStructure(): not laid out, ignoring
I/chatty: uid=10206(u0_a206) com.espressif.wifi_provisioning identical 1 line
W/View: dispatchProvideAutofillStructure(): not laid out, ignoring
I/AssistStructure: Flattened final assist data: 3196 bytes, containing 1 windows, 13 views
I/zygote64: Do full code cache collection, code=234KB, data=195KB
I/zygote64: After code cache collection, code=231KB, data=151KB
D/ProofOfPossessionActivity: POP : abcd1234
I/TextInputLayout: EditText added is not a TextInputEditText. Please switch to using that class instead.
I/TextInputLayout: EditText added is not a TextInputEditText. Please switch to using that class instead.
W/View: dispatchProvideAutofillStructure(): not laid out, ignoring
I/chatty: uid=10206(u0_a206) com.espressif.wifi_provisioning identical 1 line
W/View: dispatchProvideAutofillStructure(): not laid out, ignoring
I/AssistStructure: Flattened final assist data: 4016 bytes, containing 1 windows, 16 views
I/zygote64: Do partial code cache collection, code=251KB, data=182KB
I/zygote64: After code cache collection, code=251KB, data=182KB
    Increasing code cache capacity to 1024KB
D/ProvisionActivity: Selected AP -8BitizAP
E/Espressif::SoftAPTransport: Failed to connect to /192.168.4.1:80
W/System.err: java.net.ConnectException: Failed to connect to /192.168.4.1:80
        at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:143)
        at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
        at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
        at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
        at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:538)
        at com.espressif.provisioning.transport.SoftAPTransport.sendPostRequest(SoftAPTransport.java:69)
        at com.espressif.provisioning.transport.SoftAPTransport.access$000(SoftAPTransport.java:38)
W/System.err:     at com.espressif.provisioning.transport.SoftAPTransport$1.run(SoftAPTransport.java:111)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
    java.lang.RuntimeException: Error ! Connection Lost
        at com.espressif.provisioning.transport.SoftAPTransport.sendPostRequest(SoftAPTransport.java:88)
        at com.espressif.provisioning.transport.SoftAPTransport.access$000(SoftAPTransport.java:38)
W/System.err:     at com.espressif.provisioning.transport.SoftAPTransport$1.run(SoftAPTransport.java:111)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
D/ESP:ESPDevice: disableOnlyWifiNetwork()
D/NetdClient: setNetworkForTarget(0)
W/System.err: java.lang.IllegalArgumentException: Null input buffer
        at javax.crypto.Cipher.update(Cipher.java:1356)
        at com.espressif.provisioning.security.Security1.decrypt(Security1.java:208)
        at com.espressif.provisioning.Session$2.onSuccess(Session.java:131)
        at com.espressif.provisioning.transport.SoftAPTransport$1.run(SoftAPTransport.java:112)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
D/ESP:ESPDevice: disableOnlyWifiNetwork()
E/ESP:ESPDevice: Lost Network Connection - 3
W/EventBus: Subscriber to unregister was not registered before: class com.espressif.ui.activities.ProvisionActivity

>

**Comment by shahpiyushv** [comment]
@gulkanguner the last step can fail for the following reason:

ESP chips have 2 interfaces, station and softAP, but a single antenna. So, when the device receives the Wi-Fi network credentials, and tries connecting to the target AP using the station interface, the softAP channel also switches to the target APs channel. While this channel switches, some Android phones have a tendency to immediately disconnect and reconnect to some other saved network. You can see this in the log (`E/ESP:ESPDevice: Lost Network Connection - 3
`). Since the connection has dropped, the phone cannot query the status and so the failure is seen.

We are experimenting internally to see how this can be mitigated.

**Comment by gulkanguner** [comment]
@shahpiyushv okay, thank you very much for your help and detailed description.
