### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/crypto/tink/subtle/X25519;

### ISSUE THREAD

**Issue by chsaudio** [espressif/esp-idf-provisioning-android#39]
If We create a Library with this we are facing issue as
  java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/crypto/tink/subtle/X25519;
        at com.espressif.provisioning.security.Security1.generateKeyPair(Security1.java:199)
        at com.espressif.provisioning.security.Security1.getStep0Request(Security1.java:98)
        at com.espressif.provisioning.security.Security1.getNextRequestInSession(Security1.java:78)
        at com.espressif.provisioning.Session.init(Session.java:82)
        at com.espressif.provisioning.ESPDevice.initSession(ESPDevice.java:558)
        at com.espressif.provisioning.ESPDevice.scanNetworks(ESPDevice.java:461)
        at com.espressif.provisioning.appConnect.ProvisionConnect.startWifiScanning(ProvisionConnect.java:111)
        at com.jio.provisiontest.MainActivity.onBLEDeviceConnectionEvent(MainActivity.java:74)
        at java.lang.reflect.Method.invoke(Native Method)
        at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:507)
        at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:501)
        at org.greenrobot.eventbus.HandlerPoster.handleMessage(HandlerPoster.java:67)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6626)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.crypto.tink.subtle.X25519" on path: DexPathList[[zip file "/data/app/com.jio.provisiontest-n24Ll1Ak33nxkuWvGbrCgg==/base.apk"],nativeLibraryDirectories=[/data/app/com.jio.provisiontest-n24Ll1Ak33nxkuWvGbrCgg==/lib/arm, /system/lib, /system/vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
[issue.txt](https://github.com/espressif/esp-idf-provisioning-android/files/6021700/issue.txt)

**Comment by khushbushah2302** [comment]
Hi @chsaudio ,

Can you please check with new version of library ?

**Comment by ulrickpsp** [comment]
You should add the dependencies in your binding library as .jar files:

    implementation 'com.google.protobuf:protobuf-lite:3.0.1'
    implementation 'com.google.crypto.tink:tink-android:1.1.0'

Just download them and add them to the binding library with buildAction property set to 'EmbeddedReferenceJar'.

Good luck

**Comment by khushbushah2302** [comment]
@chsaudio , please check with the new lib version (lib-2.0.10) and close this issue if it is resolved.

**Comment by shiv19** [comment]
@khushbushah2302, Thanks! 2.0.10 fixed a dependency conflict between protobuf-lite and protobuf-javalite for me

```
Duplicate class com.google.protobuf.WireFormat$Utf8Validation$3 found in modules jetified-protobuf-javalite-3.14.0 (com.google.protobuf:protobuf-javalite:3.14.0) and jetified-protobuf-lite-3.0.1 (com.google.protobuf:protobuf-lite:3.0.1)
```
