### ISSUE TITLE
Write to BLE failed

### ISSUE THREAD

**Issue by tobyloki** [espressif/esp-idf-provisioning-android#51]
My BLE provisioning flow is as follows:
1. I start the provisioning process by scanning for BLE devices.
2. I connect to the device.
3. I make a request via `provisionManager.getEspDevice().sendDataToCustomEndPoint` and get back some data from the device.
4. Then I connect to a Wifi network and provision.

Here's my test case:
1. I run the provisioning flow listed above once with an incorrect WiFi password.
2. The provisioning fails and the ESP32 automatically resets, and I restart the provisioning flow again.
3. Step 3 of the provisioning flow is where I get the error shown below.

```
2021-08-07 21:01:44.132 29608-29627/com.test W/System.err: java.lang.Exception: Write to BLE failed
2021-08-07 21:01:44.133 29608-29627/com.test W/System.err:     at com.espressif.provisioning.transport.BLETransport$1.onCharacteristicWrite(BLETransport.java:354)
2021-08-07 21:01:44.134 29608-29627/com.test W/System.err:     at android.bluetooth.BluetoothGatt$1$7.run(BluetoothGatt.java:473)
2021-08-07 21:01:44.134 29608-29627/com.test W/System.err:     at android.bluetooth.BluetoothGatt.runOrQueueCallback(BluetoothGatt.java:860)
2021-08-07 21:01:44.135 29608-29627/com.test W/System.err:     at android.bluetooth.BluetoothGatt.access$200(BluetoothGatt.java:45)
2021-08-07 21:01:44.135 29608-29627/com.test W/System.err:     at android.bluetooth.BluetoothGatt$1.onCharacteristicWrite(BluetoothGatt.java:468)
2021-08-07 21:01:44.136 29608-29627/com.test W/System.err:     at android.bluetooth.IBluetoothGattCallback$Stub.onTransact(IBluetoothGattCallback.java:265)
2021-08-07 21:01:44.138 29608-29627/com.test W/System.err:     at android.os.Binder.execTransactInternal(Binder.java:1021)
2021-08-07 21:01:44.139 29608-29627/com.test W/System.err:     at android.os.Binder.execTransact(Binder.java:994)
2021-08-07 21:01:44.140 29608-29608/com.test W/System.err: java.lang.Exception: Write to BLE failed
2021-08-07 21:01:44.141 29608-29608/com.test W/System.err:     at com.espressif.provisioning.transport.BLETransport$1.onCharacteristicWrite(BLETransport.java:354)
2021-08-07 21:01:44.141 29608-29608/com.test W/System.err:     at android.bluetooth.BluetoothGatt$1$7.run(BluetoothGatt.java:473)
2021-08-07 21:01:44.142 29608-29608/com.test W/System.err:     at android.bluetooth.BluetoothGatt.runOrQueueCallback(BluetoothGatt.java:860)
2021-08-07 21:01:44.143 29608-29608/com.test W/System.err:     at android.bluetooth.BluetoothGatt.access$200(BluetoothGatt.java:45)
2021-08-07 21:01:44.144 29608-29608/com.test W/System.err:     at android.bluetooth.BluetoothGatt$1.onCharacteristicWrite(BluetoothGatt.java:468)
2021-08-07 21:01:44.144 29608-29608/com.test W/System.err:     at android.bluetooth.IBluetoothGattCallback$Stub.onTransact(IBluetoothGattCallback.java:265)
2021-08-07 21:01:44.145 29608-29608/com.test W/System.err:     at android.os.Binder.execTransactInternal(Binder.java:1021)
2021-08-07 21:01:44.145 29608-29608/com.test W/System.err:     at android.os.Binder.execTransact(Binder.java:994)
2021-08-07 21:01:44.145 29608-29608/com.test I/BLELandingViewModel: Write to BLE failed
2021-08-07 21:01:44.167 29608-29974/com.test W/libEGL: EGLNativeWindowType 0x71767b7d10 disconnect failed
2021-08-07 21:01:44.207 29608-29608/com.test I/MultiWindowDecorSupport: updateCaptionType >> DecorView@f010a[], isFloating: true, isApplication: true, hasWindowDecorCaption: false, hasWindowControllerCallback: false
```

Why does this error occur and how can I fix it?

I am also using ` implementation 'com.github.espressif:esp-idf-provisioning-android:lib-2.0.9'` in my applications gradle file.

**Comment by khushbushah2302** [comment]
Hi @tobyloki , thanks for reporting the issue. Will check this.

**Comment by tobyloki** [comment]
@khushbushah2302 Hi. Have you found a solution to this problem?

**Comment by khushbushah2302** [comment]
Hi @tobyloki , I am working on this issue.

**Comment by FabianTerhorst** [comment]
@tobyloki You still have the issue or you got it resolved? I have the same issue now.

**Comment by cliut** [comment]
@tobyloki You still have the issue? I have the same issue now.

**Comment by FabianTerhorst** [comment]
> @tobyloki You still have the issue? I have the same issue now.

One fix is to switch to security0.

**Comment by cliut** [comment]
> > @tobyloki You still have the issue? I have the same issue now.
> 
> One fix is to switch to security0.

Already built the firmware and ios app using security1. So want to keep using security1. Is there any way to fix this in security1?

**Comment by valientegaston** [comment]
Same issue here with security 2. Any clue? Thanks
