### ISSUE TITLE
ScanNetworks produce an Failed to create session error

### ISSUE THREAD

**Issue by juanirow** [espressif/esp-idf-provisioning-android#52]
The connection fails when I try to scan networks when a BLE device is already connected.
My Flow is: 

1. Scan for BLE devices: 
`manager.searchBleEspDevices(this)`
2. Create the ESPDevice when the device is found:
`manager.createESPDevice(ESPConstants.TransportType.TRANSPORT_BLE,ESPConstants.SecurityType.SECURITY_1)`
`manager.espDevice.connectBLEDevice(device, serviceUUID)`

3. Try to scan for Networks
`manager.espDevice.proofOfPossession = "POP_VALUE"`
`manager.espDevice.scanNetworks(this)`

Then I always receive the onWiFiScanFailed error: 
```
E/ProvisionManager: NAILAH onWiFiScanFailed: java.lang.RuntimeException: Failed to create session.
    java.lang.RuntimeException: Failed to create session.
        at com.espressif.provisioning.ESPDevice$3.onFailure(ESPDevice.java:475)
        at com.espressif.provisioning.ESPDevice$6.OnSessionEstablishFailed(ESPDevice.java:570)
        at com.espressif.provisioning.Session$1.onFailure(Session.java:108)
        at com.espressif.provisioning.transport.BLETransport$1.onCharacteristicWrite(BLETransport.java:354)
        at android.bluetooth.BluetoothGatt$1$7.run(BluetoothGatt.java:474)
        at android.bluetooth.BluetoothGatt.runOrQueueCallback(BluetoothGatt.java:882)
        at android.bluetooth.BluetoothGatt.access$200(BluetoothGatt.java:42)
        at android.bluetooth.BluetoothGatt$1.onCharacteristicWrite(BluetoothGatt.java:469)
        at android.bluetooth.IBluetoothGattCallback$Stub.onTransact(IBluetoothGattCallback.java:267)
        at android.os.Binder.execTransactInternal(Binder.java:1195)
        at android.os.Binder.execTransact(Binder.java:1159)
```

I even tried this in the application in this repository and got the same problem.

**Comment by MhtSuthar** [comment]
Hi @juanirow, 
I am facing this issue what i need to do?

I am having ESP32 device and try to connect via BLE 
I don't have any POP value so i enter blank but after the device is not sending WIFI list and session is closed.

**Comment by juanirow** [comment]
Hello, for me, it was the wrong POP at the end. According to the documentation, if you do not have a POP, you only need to send an empty string. If you have the same behavior as the previous description, maybe your device was configured with a POP different than an empty string
