### ISSUE TITLE
com.espressif.wifi_provisioning E/ESP:BleScanner: onScanFailed, errorCode:2

### ISSUE THREAD

**Issue by cunyun** [espressif/esp-idf-provisioning-android#69]
use mobile phone install this App，You keep searching, about half an hour later，it will coredump.
Once this problem occurs, the app cannot be used again, and the phone needs to be restarted！

2022-09-22 16:20:14.384 31952-31952/com.espressif.wifi_provisioning I/HwCameraUtil: notifySurfaceFlingerCameraStatus : isFront = false , isOpend = false
2022-09-22 16:20:14.464 31952-31952/com.espressif.wifi_provisioning I/ViewRootImpl: jank_removeInvalidNode jank list is null
2022-09-22 16:20:14.465 31952-31952/com.espressif.wifi_provisioning E/ESP:ESPProvisionManager: Search for BLE devices
2022-09-22 16:20:14.466 31952-31952/com.espressif.wifi_provisioning D/ESP:BleScanner: Starting BLE device scanning...
2022-09-22 16:20:14.466 31952-31952/com.espressif.wifi_provisioning I/BluetoothAdapter: getBluetoothLeScanner
2022-09-22 16:20:14.468 31952-31952/com.espressif.wifi_provisioning D/BluetoothAdapter: isLeEnabled(): ON
2022-09-22 16:20:14.472 31952-13555/com.espressif.wifi_provisioning D/BluetoothLeScanner: onScannerRegistered() - status=133 scannerId=0 mScannerId=0
2022-09-22 16:20:14.474 31952-31952/com.espressif.wifi_provisioning E/ESP:BleScanner: onScanFailed, errorCode:2
2022-09-22 16:20:14.497 31952-31952/com.espressif.wifi_provisioning W/System.err: java.lang.RuntimeException: BLE scanning failed with error code : 2
2022-09-22 16:20:14.498 31952-31952/com.espressif.wifi_provisioning W/System.err:     at com.espressif.provisioning.device_scanner.BleScanner$2.onScanFailed(BleScanner.java:165)
2022-09-22 16:20:14.498 31952-31952/com.espressif.wifi_provisioning W/System.err:     at android.bluetooth.le.BluetoothLeScanner$1.run(BluetoothLeScanner.java:624)
2022-09-22 16:20:14.498 31952-31952/com.espressif.wifi_provisioning W/System.err:     at android.os.Handler.handleCallback(Handler.java:907)
2022-09-22 16:20:14.498 31952-31952/com.espressif.wifi_provisioning W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:105)
2022-09-22 16:20:14.498 31952-31952/com.espressif.wifi_provisioning W/System.err:     at android.os.Looper.loop(Looper.java:216)
2022-09-22 16:20:14.498 31952-31952/com.espressif.wifi_provisioning W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7625)
2022-09-22 16:20:14.498 31952-31952/com.espressif.wifi_provisioning W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2022-09-22 16:20:14.498 31952-31952/com.espressif.wifi_provisioning W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
2022-09-22 16:20:14.498 31952-31952/com.espressif.wifi_provisioning W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
2022-09-22 16:20:14.498 31952-31952/com.espressif.wifi_provisioning D/ESP:ESPProvisionManager: onFailure
2022-09-22 16:20:14.498 31952-31952/com.espressif.wifi_provisioning D/ESP:ESPProvisionManager: isDeviceFound : false
2022-09-22 16:20:14.499 31952-31952/com.espressif.wifi_provisioning D/ESP:ESPProvisionManager: searchCnt : 1
2022-09-22 16:20:14.999 31952-31952/com.espressif.wifi_provisioning E/ESP:ESPProvisionManager: Search for BLE devices
2022-09-22 16:20:15.001 31952-31952/com.espressif.wifi_provisioning D/ESP:BleScanner: Starting BLE device scanning...
2022-09-22 16:20:15.001 31952-31952/com.espressif.wifi_provisioning I/BluetoothAdapter: getBluetoothLeScanner
2022-09-22 16:20:15.004 31952-31952/com.espressif.wifi_provisioning D/BluetoothAdapter: isLeEnabled(): ON
2022-09-22 16:20:15.014 31952-13555/com.espressif.wifi_provisioning D/BluetoothLeScanner: onScannerRegistered() - status=133 scannerId=0 mScannerId=0
2022-09-22 16:20:15.017 31952-31952/com.espressif.wifi_provisioning E/ESP:BleScanner: onScanFailed, errorCode:2
2022-09-22 16:20:15.018 31952-31952/com.espressif.wifi_provisioning W/System.err: java.lang.RuntimeException: BLE scanning failed with error code : 2
2022-09-22 16:20:15.019 31952-31952/com.espressif.wifi_provisioning W/System.err:     at com.espressif.provisioning.device_scanner.BleScanner$2.onScanFailed(BleScanner.java:165)
2022-09-22 16:20:15.019 31952-31952/com.espressif.wifi_provisioning W/System.err:     at android.bluetooth.le.BluetoothLeScanner$1.run(BluetoothLeScanner.java:624)
2022-09-22 16:20:15.019 31952-31952/com.espressif.wifi_provisioning W/System.err:     at android.os.Handler.handleCallback(Handler.java:907)
2022-09-22 16:20:15.019 31952-31952/com.espressif.wifi_provisioning W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:105)
2022-09-22 16:20:15.019 31952-31952/com.espressif.wifi_provisioning W/System.err:     at android.os.Looper.loop(Looper.java:216)
2022-09-22 16:20:15.019 31952-31952/com.espressif.wifi_provisioning W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7625)
2022-09-22 16:20:15.019 31952-31952/com.espressif.wifi_provisioning W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2022-09-22 16:20:15.019 31952-31952/com.espressif.wifi_provisioning W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
2022-09-22 16:20:15.019 31952-31952/com.espressif.wifi_provisioning W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
2022-09-22 16:20:15.019 31952-31952/com.espressif.wifi_provisioning D/ESP:ESPProvisionManager: onFailure
2022-09-22 16:20:15.019 31952-31952/com.espressif.wifi_provisioning D/ESP:ESPProvisionManager: isDeviceFound : false
2022-09-22 16:20:15.019 31952-31952/com.espressif.wifi_provisioning D/ESP:ESPProvisionManager: searchCnt : 2
2022-09-22 16:20:15.532 31952-31952/com.espressif.wifi_provisioning E/ESP:ESPProvisionManager: Search for BLE devices
2022-09-22 16:20:15.533 31952-31952/com.espressif.wifi_provisioning D/ESP:BleScanner: Starting BLE device scanning...
2022-09-22 16:20:15.534 31952-31952/com.espressif.wifi_provisioning I/BluetoothAdapter: getBluetoothLeScanner
2022-09-22 16:20:15.537 31952-31952/com.espressif.wifi_provisioning D/BluetoothAdapter: isLeEnabled(): ON
2022-09-22 16:20:15.546 31952-13555/com.espressif.wifi_provisioning D/BluetoothLeScanner: onScannerRegistered() - status=133 scannerId=0 mScannerId=0
2022-09-22 16:20:15.552 31952-31952/com.espressif.wifi_provisioning E/ESP:BleScanner: onScanFailed, errorCode:2
2022-09-22 16:20:15.553 31952-31952/com.espressif.wifi_provisioning W/System.err: java.lang.RuntimeException: BLE scanning failed with error code : 2
2022-09-22 16:20:15.553 31952-31952/com.espressif.wifi_provisioning W/System.err:     at com.espressif.provisioning.device_scanner.BleScanner$2.onScanFailed(BleScanner.java:165)
2022-09-22 16:20:15.553 31952-31952/com.espressif.wifi_provisioning W/System.err:     at android.bluetooth.le.BluetoothLeScanner$1.run(BluetoothLeScanner.java:624)
2022-09-22 16:20:15.553 31952-31952/com.espressif.wifi_provisioning W/System.err:     at android.os.Handler.handleCallback(Handler.java:907)
2022-09-22 16:20:15.553 31952-31952/com.espressif.wifi_provisioning W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:105)
2022-09-22 16:20:15.553 31952-31952/com.espressif.wifi_provisioning W/System.err:     at android.os.Looper.loop(Looper.java:216)
2022-09-22 16:20:15.553 31952-31952/com.espressif.wifi_provisioning W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7625)
2022-09-22 16:20:15.553 31952-31952/com.espressif.wifi_provisioning W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2022-09-22 16:20:15.554 31952-31952/com.espressif.wifi_provisioning W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
2022-09-22 16:20:15.554 31952-31952/com.espressif.wifi_provisioning W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
2022-09-22 16:20:15.554 31952-31952/com.espressif.wifi_provisioning D/ESP:ESPProvisionManager: onFailure
2022-09-22 16:20:15.554 31952-31952/com.espressif.wifi_provisioning D/ESP:ESPProvisionManager: isDeviceFound : false
2022-09-22 16:20:15.554 31952-31952/com.espressif.wifi_provisioning D/ESP:ESPProvisionManager: searchCnt : 3
2022-09-22 16:20:15.554 31952-31952/com.espressif.wifi_provisioning E/AddDeviceActivity: Error : WIFI_E7B37C device not found
2022-09-22 16:20:15.617 31952-32061/com.espressif.wifi_provisioning D/OpenGLRenderer:   HWUI Binary is  enabled
2022-09-22 16:20:15.617 31952-32061/com.espressif.wifi_provisioning D/OpenGLRenderer: disableOutlineDraw is true
2022-09-22 16:20:15.640 31952-31952/com.espressif.wifi_provisioning D/ZrHung.AppEyeUiProbe: stop checker.
2022-09-22 16:20:15.728 31952-32061/com.espressif.wifi_provisioning D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
2022-09-22 16:20:15.733 31952-32061/com.espressif.wifi_provisioning D/OpenGLRenderer:   HWUI Binary is  enabled
2022-09-22 16:20:15.733 31952-32061/com.espressif.wifi_provisioning D/OpenGLRenderer: disableOutlineDraw is true
2022-09-22 16:20:15.738 31952-31952/com.espressif.wifi_provisioning D/ZrHung.AppEyeUiProbe: notify runnable to start.
2022-09-22 16:20:15.739 31952-31952/com.espressif.wifi_provisioning E/GzwxApplication: onActivityResumed:
2022-09-22 16:20:15.766 31952-31952/com.espressif.wifi_provisioning W/InputMethodManager: startInputReason = 1
2022-09-22 16:20:15.782 31952-32061/com.espressif.wifi_provisioning D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
2022-09-22 16:20:16.037 31952-31952/com.espressif.wifi_provisioning I/SurfaceView: delay destroy surface control
2022-09-22 16:20:16.039 31952-32061/com.espressif.wifi_provisioning W/libEGL: EGLNativeWindowType 0x723b29d010 disconnect failed
2022-09-22 16:20:16.050 31952-31952/com.espressif.wifi_provisioning I/SurfaceView: need destroy surface control
2022-09-22 16:20:16.050 31952-31952/com.espressif.wifi_provisioning D/ViewRootImpl[AddDeviceActivity]: surface should not be released
2022-09-22 16:20:16.052 31952-31952/com.espressif.wifi_provisioning D/ActivityThread: Remove activity client record, r= ActivityRecord{5b1d7ec token=android.os.BinderProxy@f6fc51d {com.espressif.wifi_provisioning/com.espressif.ui.activities.AddDeviceActivity}} token= android.os.BinderProxy@f6fc51d
2022-09-22 16:20:19.088 31952-32061/com.espressif.wifi_provisioning W/libEGL: EGLNativeWindowType 0x723b31d010 disconnect failed
2022-09-22 16:20:20.474 31952-31952/com.espressif.wifi_provisioning D/ESP:BleScanner: Stop BLE device scan
2022-09-22 16:20:20.477 31952-31952/com.espressif.wifi_provisioning D/BluetoothAdapter: isLeEnabled(): ON
2022-09-22 16:20:20.478 31952-31952/com.espressif.wifi_provisioning D/BluetoothLeScanner: could not find callback wrapper
2022-09-22 16:20:20.478 31952-31952/com.espressif.wifi_provisioning D/ESP:ESPProvisionManager: scanCompleted
2022-09-22 16:20:20.478 31952-31952/com.espressif.wifi_provisioning D/ESP:ESPProvisionManager: isDeviceFound : false
2022-09-22 16:20:20.478 31952-31952/com.espressif.wifi_provisioning D/ESP:ESPProvisionManager: searchCnt : 3
2022-09-22 16:20:20.479 31952-31952/com.espressif.wifi_provisioning E/AddDeviceActivity: Error : WIFI_E7B37C device not found
2022-09-22 16:20:20.508 31952-32061/com.espressif.wifi_provisioning D/OpenGLRenderer:   HWUI Binary is  enabled
2022-09-22 16:20:20.509 31952-32061/com.espressif.wifi_provisioning D/OpenGLRenderer: disableOutlineDraw is true
2022-09-22 16:20:20.577 31952-32061/com.espressif.wifi_provisioning D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
2022-09-22 16:20:20.581 31952-32061/com.espressif.wifi_provisioning D/OpenGLRenderer:   HWUI Binary is  enabled
2022-09-22 16:20:20.581 31952-32061/com.espressif.wifi_provisioning D/OpenGLRenderer: disableOutlineDraw is true
2022-09-22 16:20:21.014 31952-31952/com.espressif.wifi_provisioning D/ESP:BleScanner: Stop BLE device scan
2022-09-22 16:20:21.017 31952-31952/com.espressif.wifi_provisioning D/BluetoothAdapter: isLeEnabled(): ON
2022-09-22 16:20:21.017 31952-31952/com.espressif.wifi_provisioning D/BluetoothLeScanner: could not find callback wrapper
2022-09-22 16:20:21.017 31952-31952/com.espressif.wifi_provisioning D/ESP:ESPProvisionManager: scanCompleted
2022-09-22 16:20:21.017 31952-31952/com.espressif.wifi_provisioning D/ESP:ESPProvisionManager: isDeviceFound : false
2022-09-22 16:20:21.017 31952-31952/com.espressif.wifi_provisioning D/ESP:ESPProvisionManager: searchCnt : 3
2022-09-22 16:20:21.018 31952-31952/com.espressif.wifi_provisioning E/AddDeviceActivity: Error : WIFI_E7B37C device not found
2022-09-22 16:20:21.034 31952-32061/com.espressif.wifi_provisioning W/libEGL: EGLNativeWindowType 0x723b31d010 disconnect failed
2022-09-22 16:20:21.072 31952-32061/com.espressif.wifi_provisioning D/OpenGLRenderer:   HWUI Binary is  enabled
2022-09-22 16:20:21.072 31952-32061/com.espressif.wifi_provisioning D/OpenGLRenderer: disableOutlineDraw is true
2022-09-22 16:20:21.166 31952-32061/com.espressif.wifi_provisioning D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
2022-09-22 16:20:21.169 31952-32061/com.espressif.wifi_provisioning D/OpenGLRenderer:   HWUI Binary is  enabled
2022-09-22 16:20:21.169 31952-32061/com.espressif.wifi_provisioning D/OpenGLRenderer: disableOutlineDraw is true
2022-09-22 16:20:21.547 31952-31952/com.espressif.wifi_provisioning D/ESP:BleScanner: Stop BLE device scan
2022-09-22 16:20:21.550 31952-31952/com.espressif.wifi_provisioning D/BluetoothAdapter: isLeEnabled(): ON
2022-09-22 16:20:21.551 31952-31952/com.espressif.wifi_provisioning D/BluetoothLeScanner: could not find callback wrapper
2022-09-22 16:20:21.551 31952-31952/com.espressif.wifi_provisioning D/ESP:ESPProvisionManager: scanCompleted
2022-09-22 16:20:21.551 31952-31952/com.espressif.wifi_provisioning D/ESP:ESPProvisionManager: isDeviceFound : false
2022-09-22 16:20:21.551 31952-31952/com.espressif.wifi_provisioning D/ESP:ESPProvisionManager: searchCnt : 3
2022-09-22 16:20:21.551 31952-31952/com.espressif.wifi_provisioning E/AddDeviceActivity: Error : WIFI_E7B37C device not found
2022-09-22 16:20:21.569 31952-32061/com.espressif.wifi_provisioning W/libEGL: EGLNativeWindowType 0x723b31d010 disconnect failed
2022-09-22 16:20:21.605 31952-32061/com.espressif.wifi_provisioning D/OpenGLRenderer:   HWUI Binary is  enabled
2022-09-22 16:20:21.606 31952-32061/com.espressif.wifi_provisioning D/OpenGLRenderer: disableOutlineDraw is true
2022-09-22 16:20:21.605 31952-32061/com.espressif.wifi_provisioning D/OpenGLRenderer:   HWUI Binary is  enabled
2022-09-22 16:20:21.606 31952-32061/com.espressif.wifi_provisioning D/OpenGLRenderer: disableOutlineDraw is true
2022-09-22 16:20:21.635 31952-32061/com.espressif.wifi_provisioning D/OpenGLRenderer:   HWUI Binary is  enabled
2022-09-22 16:20:21.635 31952-32061/com.espressif.wifi_provisioning D/OpenGLRenderer: disableOutlineDraw is true
2022-09-22 16:20:21.688 31952-32061/com.espressif.wifi_provisioning D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
2022-09-22 16:20:25.070 31952-32061/com.espressif.wifi_provisioning W/libEGL: EGLNativeWindowType 0x723b31d010 disconnect failed
2022-09-22 16:20:55.246 31952-31952/com.espressif.wifi_provisioning W/InputMethodManager: startInputReason = 8
2022-09-22 16:20:55.459 31952-31952/com.espressif.wifi_provisioning D/ZrHung.AppEyeUiProbe: stop checker.
2022-09-22 16:20:55.564 31952-31952/com.espressif.wifi_provisioning D/ViewRootImpl[EspMainActivity]: surface should not be released
2022-09-22 16:20:56.003 31952-32061/com.espressif.wifi_provisioning W/libEGL: EGLNativeWindowType 0x7259687010 disconnect failed
2022-09-22 16:20:56.026 31952-31952/com.espressif.wifi_provisioning V/ActivityThread: Handle window ActivityRecord{ed7067a token=android.os.BinderProxy@51c9e74 {com.espressif.wifi_provisioning/com.espressif.ui.activities.EspMainActivity}} visibility: false
2022-09-22 16:20:56.259 31952-32026/com.espressif.wifi_provisioning D/ZrHung.AppEyeUiProbe: Current Activity:false
2022-09-22 16:20:56.259 31952-32026/com.espressif.wifi_provisioning D/ZrHung.AppEyeUiProbe: not watching, wait.

**Comment by khushbushah2302** [comment]
Hi @cunyun , can you check with latest app ?
