### ISSUE TITLE
Provision Issue -  java.lang.RuntimeException: Characteristic is not available for given path.

### ISSUE THREAD

**Issue by vincalkr** [espressif/esp-idf-provisioning-android#83]
Hi

I ask those who know more than me about this ESP32 card, for a problem with provisioning.

ERROR:
java.lang.RuntimeException: Characteristic is not available for given path.
at com.espressif.provisioning.transport.BLETransport.sendConfigData(BLETransport.java:124)
at com.espressif.provisioning.Session.init(Session.java:92)
at com.espressif.provisioning.ESPDevice.initSession(ESPDevice.java:652)
at com.espressif.provisioning.ESPDevice.provision(ESPDevice.java:569)
at com.albicchiere.DeviceFinder.connectDevice(DeviceFinder.java:166)
at java.lang.reflect.Method.invoke(Native Method)
at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
at android.os.Handler.handleCallback(Handler.java:751)
at android.os.Handler.dispatchMessage(Handler.java:95)
at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
at android.os.Looper.loop(Looper.java:154)
at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
at java.lang.Thread.run(Thread.java:762)

I call this code:

ESPProvisionManager.getInstance(getReactApplicationContext()).createESPDevice(ESPConstants.TransportType.TRANSPORT_BLE, ESPConstants.SecurityType.SECURITY_1);
ESPDevice espDevice = ESPProvisionManager.getInstance(getReactApplicationContext()).getEspDevice();

espDevice.connectBLEDevice(device.getBluetoothDevice(), uuids.get(indexFound));
espDevice.setProofOfPossession("abcd1234");
espDevice.provision(ssid, password, provisionListener);

Thank you

**Comment by krystek-dev** [comment]
you have to put characteristic descriptor name to path, not characteristic UUID
