### ISSUE TITLE
Unable to call ProvisionListener in Kotlin Android

### ISSUE THREAD

**Issue by adammizam** [espressif/esp-idf-provisioning-android#86]
I'm new in kotlin android development, I have encounter one issue that unable to send the information for Provision. It keep crashing during testing and the error is 'int java.lang.String.length()' on a null object reference.
Below is an example of my test code:

```
provisionManager.espDevice.provision(ssidValue, passphraseValue, object : ProvisionListener
        {
            override fun createSessionFailed(e: Exception) {
                runOnUiThread {
                    Toast.makeText(applicationContext, "Create Session Failed", Toast.LENGTH_LONG).show()
                }
            }

            override fun wifiConfigSent() {
                runOnUiThread {
                    Toast.makeText(applicationContext, "Wifi Config Sent", Toast.LENGTH_LONG).show()
                }
            }

            override fun wifiConfigFailed(e: Exception) {
                runOnUiThread {
                    Toast.makeText(applicationContext, "Wifi Config Failed", Toast.LENGTH_LONG).show()
                }
            }

            override fun wifiConfigApplied() {
                runOnUiThread {
                    Toast.makeText(applicationContext, "Wifi Config Applied", Toast.LENGTH_LONG).show()
                }
            }

            override fun wifiConfigApplyFailed(e: Exception) {
                runOnUiThread {
                    Toast.makeText(applicationContext, "Wifi Config Apply Failed", Toast.LENGTH_LONG).show()
                }
            }

            override fun provisioningFailedFromDevice(failureReason: ProvisionFailureReason) {
                runOnUiThread {
                    when (failureReason) {
                        ProvisionFailureReason.AUTH_FAILED -> Toast.makeText(applicationContext, "Authentication Failed", Toast.LENGTH_LONG).show()
                        ProvisionFailureReason.NETWORK_NOT_FOUND -> Toast.makeText(applicationContext, "Network Not Found", Toast.LENGTH_LONG).show()
                        ProvisionFailureReason.DEVICE_DISCONNECTED, ProvisionFailureReason.UNKNOWN -> Toast.makeText(applicationContext, "Device disconnected", Toast.LENGTH_LONG).show()
                    }
                }
            }

            override fun deviceProvisioningSuccess() {
                runOnUiThread {
                    Toast.makeText(applicationContext, "Provisioning Success", Toast.LENGTH_LONG).show()
                }
            }

            override fun onProvisioningFailed(e: Exception) {
                runOnUiThread {
                    Toast.makeText(applicationContext, "Provisioning Failed", Toast.LENGTH_LONG).show()
                }
            }
        })
```

Below is the error: 
```
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
                                                      at org.json.JSONTokener.nextCleanInternal(JSONTokener.java:121)
                                                      at org.json.JSONTokener.nextValue(JSONTokener.java:98)
                                                      at org.json.JSONObject.<init>(JSONObject.java:168)
                                                      at org.json.JSONObject.<init>(JSONObject.java:185)
                                                      at com.espressif.provisioning.ESPDevice.initSession(ESPDevice.java:593)
                                                      at com.espressif.provisioning.ESPDevice.provision(ESPDevice.java:569)
```

**Comment by lozaning** [comment]
Did you ever figure this out @adammizam? Im stuck with the exact same problem

**Comment by ryanrampage1** [comment]
@lozaning you have any ideas on this? Im having the same issue. The actual NPE is in the following when it tries to get the version info off the BLE transport object. Just can not figure out where to set that. 

```
/**
     * This method is used to get version information to determine what features are enabled in a device and act accordingly.
     *
     * @return Returns device version information.
     */
    public String getVersionInfo() {

        if (transport instanceof BLETransport) {
            return ((BLETransport) transport).versionInfo;
        } else {
            return versionInfo;
        }
    }
```

**Comment by ryanrampage1** [comment]
Looks like this commit switched from an independent runnable to set up that version info to on the first read. No idea how this is working at all for anyone https://github.com/espressif/esp-idf-provisioning-android/commit/c202748c74b4b3b2832c467dc20494fce28c62e9

**Comment by ryanrampage1** [comment]
My quick update here, when I swapped over from `WIFI_PROV_SECURITY_1` to `WIFI_PROV_SECURITY_0` on the firmware. Guessing that is a big part of the issue.

**Comment by KhushbuShah25** [comment]
Will check the issue and update soon.

**Comment by valientegaston** [comment]
Hi! same problem here... any fix available? Thank you!

**Comment by KhushbuShah25** [comment]
@adammizam , here is how ProvisionListener is used in ProvisionActivity.
https://github.com/espressif/esp-idf-provisioning-android/blob/98b0ad1f83f62e63bd38f4af32c0db54f9b7a323/app/src/main/java/com/espressif/ui/activities/ProvisionActivity.kt#L213
